name: the espresso cup project
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17061
title: the espresso cup project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff9e9'
    - '#07060c'
    - '#917955'
    - '#664c31'
    - '#bda46e'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
