name: the espresso cup project
favicon: null
layout_spectrum: 0.2333968044258654
typography_spectrum: 0.10027962899766862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff002a'
    - '#383643'
    - '#0083ce'
    - '#ff8c3b'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
