name: the espresso cup project
favicon: null
layout_spectrum: 0.2333968044258654
typography_spectrum: 0.10027962899766862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8512290443759412
  lightness: 0.6468980135396123
  saturation: 0.7755995993502438
  rhythmicContrast: 0.047442581970244646
purpose: []
